FROM stuartferguson/txnprocbase:latest AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["VoucherManagementACL/NuGet.Config", "."]
COPY ["VoucherManagementACL/VoucherManagementACL.csproj", "VoucherManagementACL/"]
COPY ["VoucherManagementACL.DataTransferObjects/VoucherManagementACL.DataTransferObjects.csproj", "VoucherManagementACL.DataTransferObjects/"]
COPY ["VoucherManagementACL.BusinessLogic/VoucherManagementACL.BusinessLogic.csproj", "VoucherManagementACL.BusinessLogic/"]
COPY ["VoucherManagementACL.Models/VoucherManagementACL.Models.csproj", "VoucherManagementACL.Models/"]
RUN dotnet restore "VoucherManagementACL/VoucherManagementACL.csproj"
COPY . .
WORKDIR "/src/VoucherManagementACL"
RUN dotnet build "VoucherManagementACL.csproj" -c Release -o /app/build

# Sort out certificate stuff here
RUN openssl x509 -inform DER -in /src/VoucherManagementACL/aspnetapp-root-cert.cer -out /src/VoucherManagementACL/aspnetapp-root-cert.crt
RUN cp /src/VoucherManagementACL/aspnetapp-root-cert.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

FROM build AS publish
RUN dotnet publish "VoucherManagementACL.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "VoucherManagementACL.dll"]