// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VoucherManagementACL.IntegrationTests.GetVoucher
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "base")]
    [Xunit.TraitAttribute("Category", "shared")]
    public partial class GetVoucherFeature : object, Xunit.IClassFixture<GetVoucherFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = new string[] {
                "base",
                "shared"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "GetVoucher.feature"
#line hidden
        
        public GetVoucherFeature(GetVoucherFeature.FixtureData fixtureData, VoucherManagementACL_IntegrationTests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "GetVoucher", "GetVoucher", null, ProgrammingLanguage.CSharp, new string[] {
                        "base",
                        "shared"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "RoleName"});
            table1.AddRow(new string[] {
                        "VoucherRedemption"});
#line 6
 testRunner.Given("the following security roles exist", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ResourceName",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table2.AddRow(new string[] {
                        "estateManagement",
                        "Estate Managememt REST",
                        "Secret1",
                        "estateManagement",
                        "MerchantId, EstateId, role"});
            table2.AddRow(new string[] {
                        "voucherManagement",
                        "Voucher Management REST",
                        "Secret1",
                        "voucherManagement",
                        ""});
            table2.AddRow(new string[] {
                        "voucherManagementACL",
                        "Voucher Management ACL REST",
                        "Secret1",
                        "voucherManagementACL",
                        "EstateId, role, ContractId"});
#line 10
 testRunner.Given("the following api resources exist", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "AllowedScopes",
                        "AllowedGrantTypes"});
            table3.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "estateManagement,voucherManagement",
                        "client_credentials"});
            table3.AddRow(new string[] {
                        "redemptionClient",
                        "Redemption Client",
                        "Secret1",
                        "voucherManagementACL",
                        "password"});
#line 16
 testRunner.Given("the following clients exist", ((string)(null)), table3, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "ClientId"});
            table4.AddRow(new string[] {
                        "serviceClient"});
#line 21
 testRunner.Given("I have a token to access the estate management and voucher management resources", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName"});
            table5.AddRow(new string[] {
                        "Test Estate 1"});
            table5.AddRow(new string[] {
                        "Test Estate 2"});
#line 25
 testRunner.Given("I have created the following estates", ((string)(null)), table5, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName",
                        "RoleName"});
            table6.AddRow(new string[] {
                        "redemptionuser@testredemption1.co.uk",
                        "123456",
                        "TestRedemption",
                        "User1",
                        "Test Estate 1",
                        "VoucherRedemption"});
            table6.AddRow(new string[] {
                        "redemptionuser@testredemption2.co.uk",
                        "123456",
                        "TestRedemption",
                        "User2",
                        "Test Estate 2",
                        "VoucherRedemption"});
#line 30
 testRunner.Given("I have created the following security users", ((string)(null)), table6, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table7.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "True",
                        "True"});
            table7.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "True",
                        "True"});
#line 35
 testRunner.Given("I have created the following operators", ((string)(null)), table7, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "Value",
                        "TransactionId",
                        "RecipientEmail",
                        "RecipientMobile"});
            table8.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "10.00",
                        "19f2776a-4230-40d4-8cd2-3649e18732e0",
                        "testrecipient1@recipient.co.uk",
                        ""});
            table8.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "20.00",
                        "6351e047-8f31-4472-a294-787caa5fb738",
                        "",
                        "123456788"});
            table8.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "10.00",
                        "29f2776a-4230-40d4-8cd2-3649e18732e0",
                        "testrecipient1@recipient.co.uk",
                        ""});
            table8.AddRow(new string[] {
                        "Test Estate 2",
                        "Voucher",
                        "20.00",
                        "7351e047-8f31-4472-a294-787caa5fb738",
                        "",
                        "123456788"});
#line 40
 testRunner.When("I issue the following vouchers", ((string)(null)), table8, "When ");
#line hidden
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Get Vouchers")]
        [Xunit.TraitAttribute("FeatureTitle", "GetVoucher")]
        [Xunit.TraitAttribute("Description", "Get Vouchers")]
        [Xunit.TraitAttribute("Category", "PRTest")]
        public virtual void GetVouchers()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Get Vouchers", null, tagsOfScenario, argumentsOfScenario);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 49
 testRunner.Given("I am logged in as \"redemptionuser@testredemption1.co.uk\" with password \"123456\" f" +
                        "or Estate \"Test Estate 1\" with client \"redemptionClient\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "OperatorName",
                            "Value",
                            "TransactionId"});
                table9.AddRow(new string[] {
                            "Test Estate 1",
                            "Voucher",
                            "10.00",
                            "19f2776a-4230-40d4-8cd2-3649e18732e0"});
                table9.AddRow(new string[] {
                            "Test Estate 1",
                            "Voucher",
                            "20.00",
                            "6351e047-8f31-4472-a294-787caa5fb738"});
#line 51
 testRunner.When("I get the following vouchers the voucher is returned", ((string)(null)), table9, "When ");
#line hidden
#line 56
 testRunner.Given("I am logged in as \"redemptionuser@testredemption2.co.uk\" with password \"123456\" f" +
                        "or Estate \"Test Estate 2\" with client \"redemptionClient\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "EstateName",
                            "OperatorName",
                            "Value",
                            "TransactionId"});
                table10.AddRow(new string[] {
                            "Test Estate 2",
                            "Voucher",
                            "10.00",
                            "29f2776a-4230-40d4-8cd2-3649e18732e0"});
                table10.AddRow(new string[] {
                            "Test Estate 2",
                            "Voucher",
                            "20.00",
                            "7351e047-8f31-4472-a294-787caa5fb738"});
#line 58
 testRunner.When("I get the following vouchers the voucher is returned", ((string)(null)), table10, "When ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GetVoucherFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GetVoucherFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
