name: Nightly Build

on:
  schedule:
  - cron: "10 23 * * *"
  repository_dispatch:

jobs:
  build:
    name: "Nightly Build"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set Up Variables
      run: echo "action_url=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_ENV

    - name: Install NET 7
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.x'

    - name: Restore Nuget Packages
      run: dotnet restore VoucherManagementACL.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json

    - name: Build Code
      run: dotnet build VoucherManagementACL.sln --configuration Release
        
    - name: Run Unit Tests
      run: |
        echo "ASPNETCORE_ENVIRONMENT are > ${ASPNETCORE_ENVIRONMENT}"
        dotnet test "VoucherManagementACL.Tests\VoucherManagementACL.Tests.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov1.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"                        
        dotnet test "VoucherManagementACL.BusinessLogic.Tests\VoucherManagementACL.BusinessLogic.Tests.csproj" /p:CollectCoverage=true /p:Exclude="[xunit*]*" /p:ExcludeByAttribute="Obsolete" /p:ExcludeByAttribute="GeneratedCodeAttribute" /p:ExcludeByAttribute="CompilerGeneratedAttribute" /p:ExcludeByAttribute="ExcludeFromCodeCoverageAttribute" /p:CoverletOutput="../lcov2.info" /maxcpucount:1 /p:CoverletOutputFormat="lcov"                

    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.4.4
    
    #- name: Combine Coverage
    #  run: |
    #    npm i lcov-result-merger
    #    ./node_modules/lcov-result-merger/bin/lcov-result-merger.js '*.info' 'lcov.info' 

    #- name: Upload Code Coverage
    #  uses: coverallsapp/github-action@master
    #  with:
    #      github-token: ${{ secrets.github_token }}
    #      path-to-lcov: lcov.info    
        
    - name: Build Docker Image
      run: docker build . --file VoucherManagementACL/dockerfile --tag vouchermanagementacl:latest

    - name: Run Integration Tests
      run: dotnet test "VoucherManagementACL.IntegrationTests\VoucherManagementACL.IntegrationTests.csproj"

    #- uses: nashmaniac/create-issue-action@v1.1
    #  if: ${{ failure() }}
    #  name: Create an issue on build failure
    #  with:
    #    title: Investigate Nightly Build Failure
    #    token: ${{secrets.GITHUB_TOKEN}}
    #    labels: nightlybuild
    #    body: Url is ${{env.action_url}}
